# Generated by Django 3.1.3 on 2020-11-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0002_auto_20201111_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='holiday',
        ),
        migrations.AddField(
            model_name='holiday',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_calendar.country'),
        ),
    ]
